Små endringar i nynorskfilene 🇳🇴❤️‍🔥
volrathbugge/norsk pull request #3
Opened 2022-10-01 12:28 UTC by petrepa

Spennande arbeid, karar. 

La inn eit lite forslag under laurdagslunsjen min.

Hald fram det gode arbeidet!

2022-11-05 11:20 UTC, jonassundseth requested changes
Du må oppdatere eksempelkoden også.

2022-11-05 11:20 UTC, jonassundseth commented on nynorsk.h
> +#define haldfram continue
Held er presens

2022-11-07 13:53 UTC, petrepa commented on nynorsk.h
> +#define haldfram continue
Stussa litt i den og tok nokre runder med meg sjølv. Men jøu, då vert det sånn.

2022-11-07 15:08 UTC, jonassundseth approved these changes
SBUFM

2022-11-07 15:08 UTC, merged